tolerations:
  - operator: "Exists"
image:
  repository: "mozart89/fluentbit"
  tag: "2.2.2"

luaScripts:
  dedot.lua: |
    function dedot(tag, timestamp, record)
        if record["kubernetes"] == nil then
            return 0, 0, 0
        end
        dedot_keys(record["kubernetes"]["annotations"])
        dedot_keys(record["kubernetes"]["labels"])
        return 1, timestamp, record
    end

    function dedot_keys(map)
        if map == nil then
            return
        end
        for k, v in pairs(map) do
            dedotted = string.gsub(k, "%.", "_")
            if k ~= dedotted then
                map[dedotted] = v
                map[k] = nil
            end
        end
    end

config:
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On        
    [INPUT]
        Name              tail
        Tag               nginx.*
        Path              /var/log/containers/ingress-nginx-controller*.log
        Parser            docker, cri
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
    [FILTER]
        Name lua
        Match kube.*
        script /fluent-bit/scripts/dedot.lua
        call dedot
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch-master
        Logstash_Format On
        Logstash_Prefix kube
        Retry_Limit False
        tls On
        tls.verify Off
        http_user elastic
        http_passwd Ftv3rE5i9DZXh7vJ
        Suppress_Type_Name On
        Trace_Error    On
    [OUTPUT]
        Name es
        Match nginx.*
        Host elasticsearch-master
        Logstash_Format On
        Logstash_Prefix nginx
        Retry_Limit False
        tls On
        tls.verify Off
        http_user elastic
        http_passwd Ftv3rE5i9DZXh7vJ
        Suppress_Type_Name On
        Trace_Error    On
    [OUTPUT]
        Name es
        Match host.*
        Host elasticsearch-master
        Logstash_Format On
        Logstash_Prefix host
        Retry_Limit False
        tls On
        tls.verify Off
        http_user elastic
        http_passwd Ftv3rE5i9DZXh7vJ
        Suppress_Type_Name On
        Trace_Error    On
  #   [OUTPUT]
  #       Name es
  #       Match host.*
  #       Host elasticsearch-master
  #       Logstash_Format On
  #       Logstash_Prefix node
  #       Retry_Limit False
  #       tls On
  #       tls.verify Off
  #       http_user elastic
  #       http_passwd bEghZ1CTMUTZOQ8l
  #       Suppress_Type_Name On
  # customParsers: |
  #   [PARSER]
  #       Name docker_no_time
  #       Format json
  #       Time_Keep Off
  #       Time_Key time
  #       Time_Format %Y-%m-%dT%H:%M:%S.%L