apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-pods-prometheus
subjects:
  - kind: Group
    name: system:serviceaccounts:prometheus
    namespace: prometheus
