apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  labels:
    app: nginx-exporter
spec:
  type: ClusterIP
  selector:
    app: nginx-exporter
  ports:
  - name: nginx-exporter-port
    port: 9113
