apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 10.1.0.23
     iqn: iqn.2024-03.example.com:lun1
     lun: 0
     fsType: 'ext4'
     readOnly: false