---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend
  namespace: microservices-demo
spec:
  interval: 30s
  releaseName: frontend
  chart:
    spec:
      chart: ./charts/frontend
      sourceRef:
        kind: GitRepository
        name: onlineboutique
  values:
    image:
      tag: v0.0.4
