---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recommendationservice
  namespace: microservices-demo
spec:
  interval: 30s
  releaseName: recommendationservice
  chart:
    spec:
      chart: ./charts/recommendationservice
      sourceRef:
        kind: GitRepository
        name: onlineboutique
  values:
    image:
      tag: v0.0.2
