apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: web
      image: mozart89/otus-2-web
      readinessProbe:
        httpGet:
          path: /index.html
          port: 8000
      livenessProbe:
        tcpSocket:
          port: 8000
      volumeMounts:
        - name: app
          mountPath: /app
    - name: init
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh && sleep 3600']
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
